name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update Dependencies
        run: |
          npm -g i npm-check-updates
          ncu -u
          npm install
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            commit-message: Update dependencies
            title: '[DEPENDENCY] Update Dependencies'
            body: |
                Updates dependencies in `package.json`.
            branch: update-dependencies
